{% set name = "runnerase" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/runnerase-{{ version }}.tar.gz
  sha256: 533a91bc25af203d01afbaae8d13db9e388b24572686422f02b3d7e2d82ff439

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.17.0,<2.0
    - ase >=3.19.0
    - scikit-learn >=1.2.0

test:
  imports:
    - runnerase
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://runner-suite.gitlab.io/runnerase/
  summary: An Interface between the Runner Neural Network Energy Representation (RuNNer) and the Atomic Simulation Environment (ASE).
  dev_url: https://gitlab.com/runner-suite/runnerase
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
