{% set name = "runnerase" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/runnerase-{{ version }}.tar.gz
  sha256: ff95b9f19874adf28b24e6e2d086d78027888ece86d84e1dc5e67af8dcbe8cbc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.17.0
    - ase
    - scikit-learn >=1.2.0

test:
  imports:
    - runnerase
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://runner-suite.gitlab.io/runnerase/
  summary: An Interface between the Runner Neural Network Energy Representation (RuNNer) and the Atomic Simulation Environment (ASE).
  dev_url: https://gitlab.com/runner-suite/runnerase
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
