schema_version: 1

context:
  name: runnerase
  version: "1.1.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/runnerase-${{ version }}.tar.gz
  sha256: ff95b9f19874adf28b24e6e2d086d78027888ece86d84e1dc5e67af8dcbe8cbc

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - wheel
    - pip
  run:
    - python >=${{ python_min }}
    - numpy >=1.17.0
    - ase
    - scikit-learn >=1.2.0

tests:
  - python:
      imports:
        - runnerase
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: An Interface between the Runner Neural Network Energy Representation (RuNNer) and the Atomic Simulation Environment (ASE).
  license: GPL-3.0-or-later
  license_file: LICENSE
  homepage: https://runner-suite.gitlab.io/runnerase/
  repository: https://gitlab.com/runner-suite/runnerase

extra:
  recipe-maintainers:
    - jan-janssen
